### ISSUE TITLE
June 2018 Spec compliance checklist

### ISSUE THREAD

**Issue by anmonteiro** [andreas/ocaml-graphql-server#119]
The following is an incomplete but growing list of things that we need to support to achieve compliance with the Jun 2018 version of the Spec.

- [ ] [Block strings](http://facebook.github.io/graphql/June2018/#sec-String-Value) (using `"""`)
- [ ] Check that enum values are not `true`, `false` or `null` (http://facebook.github.io/graphql/June2018/#sec-Enum-Value)
- [ ] [Field Selection Merging](http://facebook.github.io/graphql/June2018/#sec-Field-Selection-Merging)
- [ ] Validate that [fragments must be used](http://facebook.github.io/graphql/June2018/#sec-Fragments-Must-Be-Used) if defined in a document
- [x] the `errors` key [must appear first](http://facebook.github.io/graphql/June2018/#sec-Response-Format) if present (#131)
- [ ] [Schema](http://facebook.github.io/graphql/June2018/#sec-Schema-Extension) and [object](http://facebook.github.io/graphql/June2018/#sec-Object-Extensions) extensions
